name: hw16
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.2 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  google_fonts: ^5.0.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/

  # fonts:
  #   - family: Poppins
  #     fonts:
  #       - asset: fonts/Poppins/Poppins-Bold.ttf
  #       - asset: fonts/Poppins/Poppins-Medium.ttf
  #       - asset: fonts/Poppins/Poppins-Semibold.ttf
  #       - asset: fonts/Poppins/Poppins-Regular.ttf

  #   - family: Roboto
  #     fonts:
  #       - asset: fonts/Roboto/Roboto-Medium.ttf

  #   - family: Snippet
  #     fonts:
  #       - asset: fonts/Snippet/Snippet-Regular.ttf