name: hadeel_hw_16
description: A new Flutter project.
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.0.2 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - lib/App/assets/images/

  fonts:
    - family: Roboto
      fonts:
        - asset: lib/App/assets/fonts/Roboto-Regular.ttf
        - asset: lib/App/assets/fonts/Roboto-Medium.ttf
        - asset: lib/App/assets/fonts/Roboto-Light.ttf
